server:
  port: 9002
spring:
  application:
    name: customer-ui # ???????Eureka???
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultzone: http://127.0.0.1:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
feign:
  circuit breaker:
    enabled: true

