eureka:
  client:
    fetch-registry: true
    service-url:
      defaultzone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: zuul

server:
  port: 8888

#?????????
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ????????????redis???????????ribbon???????????????????ribbon?????
ribbon:
  eureka:
    enabled: true

#??????
zuul:
  routes:
    goods-ui: /goods/**
    customer-ui: /customer/**





