server:
  port: 8761 # ??
spring:
  application:
    name: eureka # ???????Eureka???
eureka:
  client:
    register-with-eureka: false # ??????????EurekaServer????true
    fetch-registry: false # ???????????????true
    service-url: # EurekaServer?????????????????????????Server????
      defaultZone: http://localhost:8761/eureka
